# Test-containers for development of sync-hole

version: "3.8"
services:
  pihole-main:
    image: pihole/pihole
    build:
      dockerfile: Dockerfile-pihole
    hostname: main
    container_name: pihole-a
    restart: unless-stopped
    environment:
      WEBPASSWORD: "admin"
      # (Re)-enable GS, when a config file exists in the system
      GS_AUTO_ENABLE: true
      GS_AUTO_DEBUG: true
    ports:
#      # Webinterface on HOST of main
      - "8080:80"
#      - "5553:53/tcp"
#      - "5553:53/udp"
    volumes:
      - ./data/main/pihole/etc/pihole:/etc/pihole
      - ./data/main/pihole/etc/dnsmasq.d:/etc/dnsmasq.d:rw

    networks:
      pihole:
        ipv4_address: 172.99.0.10

  pihole-secondary:
    image: pihole/pihole
    hostname: main
    container_name: pihole-b
    restart: unless-stopped
    environment:
      WEBPASSWORD: "admin"
      # (Re)-enable GS, when a config file exists in the system
      GS_AUTO_ENABLE: true
      GS_AUTO_DEBUG: true
    ports:
#      # Webinterface on HOST of main
      - "8081:80"
#      - "5553:53/tcp"
#      - "5553:53/udp"
    volumes:
      - ./data/secondary/pihole/etc/pihole:/etc/pihole
      - ./data/secondary/pihole/etc/dnsmasq.d:/etc/dnsmasq.d:rw

    networks:
      pihole:
        ipv4_address: 172.99.0.20




  gs-main:
    image: gs
    build: .
    hostname: gs-a
    restart: unless-stopped
    environment:
      GS_AUTO_ENABLE: true
      GS_AUTO_DEBUG: true
      LOCAL_PIHOLE_TYPE: "podman"
      REMOTE_PIHOLE_TYPE: "podman"
      LOCAL_DOCKER_CONTAINER: "pihole-a"
      REMOTE_DOCKER_CONTAINER: "pihole-b"

      LOCAL_FILE_OWNER: "999:1000"
      REMOTE_FILE_OWNER: "999:1000"
      REMOTE_HOST: "gs-b"
      REMOTE_USER: "gravitysync"
      GS_SSH_PORT: 22
      GS_SSH_PKIF: "~/.ssh/id_ed25519"

    ports:
      # SSH port on HOST of main (for DEBUGGING)
      - "2222:22"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - ./data/main/gsync:/config:rw
      - ./data/main/pihole/etc/pihole:/etc/pihole
      - ./data/main/pihole/etc/dnsmasq.d:/etc/dnsmasq.d
      - ~/.ssh/id_ed25519.pub:/config/home/.ssh/authorized_keys:ro
      - ~/.ssh/id_ed25519:/config/.ssh/id_ed25519:ro


    networks:
      pihole:

  gs-secondary:
    image: gs
    build: .
    hostname: gs-b
    restart: unless-stopped
    environment:
      GS_AUTO_ENABLE: true
      GS_AUTO_DEBUG: true
      LOCAL_PIHOLE_TYPE: "podman"
      REMOTE_PIHOLE_TYPE: "podman"
      LOCAL_DOCKER_CONTAINER: "pihole-b"
      REMOTE_DOCKER_CONTAINER: "pihole-a"

      LOCAL_FILE_OWNER: "999:1000"
      REMOTE_FILE_OWNER: "999:1000"
      REMOTE_HOST: "gs-a"
      REMOTE_USER: "gravitysync"
      GS_SSH_PORT: 22
      GS_SSH_PKIF: "~/.ssh/id_ed25519"

    ports:
      # SSH port on HOST of main (for DEBUGGING)
      - "2223:22"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - ./data/secondary/gsync:/config:rw
      - ./data/secondary/pihole/etc/pihole:/etc/pihole
      - ./data/secondary/pihole/etc/dnsmasq.d:/etc/dnsmasq.d
      - ~/.ssh/id_ed25519.pub:/config/home/.ssh/authorized_keys:ro
      - ~/.ssh/id_ed25519:/config/.ssh/id_ed25519:ro

    networks:
      pihole:



networks:
  pihole:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.99.0.0/16



# Once the containers are started up, run the following

### Retrieve link password
# docker exec -it main cat password
# docker exec -it secondary cat password

### Link main to secondary & enable automatic mode
# docker exec -it main gravity-sync configure
#   Enter IP of secondary: 10.0.0.102
#   Enter SSH user: gs
#   Confirm authenticity of host: Write 'yes'
#   Enter the link password of 'secondary'
# Now enable the automatic sync
# docker exec -it main gravity-sync auto

### OPTIONAL (but suggested): Link secondary to main & enable automatic mode
# docker exec -it secondary gravity-sync configure
#   Enter IP of main: 10.0.0.101
#   Enter SSH user: gs
#   Confirm authenticity of host: Write 'yes'
#   Enter the link password of 'main'
# Now enable the automatic sync
# docker exec -it secondary gravity-sync auto

# If you want to oberseve the automatic sync, run
# docker exec -it main gravity-sync monitor
# docker exec -it secondary gravity-sync monitor
